// 전체 이모지(1900+). 이름(영문)으로 검색되며, 자주 쓰는 것들엔 한글 키워드를 얹는다.
import data from "unicode-emoji-json";

// 한글/추가 검색 키워드 오버레이(char → 추가 키워드).
const EXTRA = {
  "🚀": "로켓 시작 배포 launch deploy",
  "▶️": "시작 실행 재생 play run",
  "⏸️": "일시정지 보류 pause",
  "⏹️": "정지 종료 stop",
  "🔁": "반복 재시도 repeat retry",
  "🔄": "새로고침 동기화 refresh sync",
  "✅": "완료 확인 done check",
  "☑️": "체크 완료",
  "❌": "취소 실패 닫기 cancel fail",
  "🏁": "종료 완료 목표 finish goal",
  "🎯": "목표 타겟 target",
  "🚧": "진행중 공사 wip",
  "🛠️": "도구 빌드 수정 tools",
  "🔧": "수정 설정 렌치 fix",
  "⚙️": "설정 톱니 settings",
  "🐛": "버그 이슈 bug",
  "🔍": "검색 찾기 리뷰 search review",
  "📝": "작성 편집 메모 write edit",
  "✏️": "편집 연필 edit",
  "📄": "문서 페이지 파일 document",
  "📋": "클립보드 목록 clipboard",
  "📌": "고정 핀 중요 pin",
  "🔀": "머지 분기 shuffle merge",
  "🌿": "브랜치 branch git",
  "🌱": "새싹 시작 new",
  "🔨": "빌드 망치 build",
  "📦": "패키지 배포 릴리즈 package release",
  "🚢": "배포 출시 ship deploy",
  "🧪": "테스트 실험 test qa",
  "👀": "리뷰 검토 review eyes",
  "💬": "코멘트 대화 comment",
  "📢": "알림 공지 announce",
  "🔔": "알림 종 notify bell",
  "⭐": "별 즐겨찾기 star",
  "✨": "새로움 반짝 sparkles new",
  "🔥": "긴급 불 fire hot urgent",
  "⚡": "빠름 번개 fast",
  "💡": "아이디어 전구 idea",
  "❗": "중요 느낌표 important",
  "❓": "질문 물음표 question",
  "⚠️": "경고 주의 warning",
  "🚨": "경보 긴급 alert",
  "🛑": "정지 stop",
  "🏷️": "라벨 태그 label tag",
  "📁": "폴더 folder",
  "📂": "폴더 열림 folder",
  "📊": "차트 통계 chart",
  "📈": "상승 성장 up growth",
  "🗓️": "일정 캘린더 calendar",
  "⏰": "마감 시간 알람 deadline",
  "⏳": "대기 모래시계 wait",
  "🔒": "잠금 보안 lock",
  "🔓": "해제 열림 unlock",
  "🔑": "키 접근 key",
  "🛡️": "방패 보안 shield",
  "👍": "좋아요 승인 thumbs up",
  "🙌": "완료 만세 done",
  "🤝": "협업 합의 handshake",
  "🙏": "부탁 감사 please thanks",
  "💪": "힘 strong",
  "🧠": "뇌 생각 brain",
  "🤖": "봇 에이전트 robot bot ai agent",
  "👤": "사용자 담당자 user person",
  "👥": "팀 사용자 team",
  "🧑‍💻": "개발자 코딩 developer",
  "💻": "노트북 개발 laptop code",
  "🎉": "축하 완료 party",
  "🏆": "우승 트로피 trophy",
  "💯": "완벽 100 perfect",
  "♻️": "재활용 재사용 recycle",
  "🧹": "정리 청소 cleanup",
  "🗑️": "삭제 휴지통 trash delete",
  "🩹": "패치 반창고 fix patch",
  "🔗": "연결 링크 link",
  "📍": "위치 핀 location",
  "🗺️": "지도 계획 map",
  "🧭": "방향 나침반 compass",
  "🚦": "상태 신호등 status",
  "🔦": "디버그 손전등 debug",
  "🧩": "조각 모듈 puzzle module",
  "☁️": "클라우드 cloud",
  "🌐": "웹 전역 web global",
  "🎨": "디자인 아트 design art",
  "🔬": "분석 현미경 analyze",
};

// 원본 그룹명(영문) → 표시용 한글 라벨. 노션식 카테고리 헤더에 사용.
export const GROUP_LABELS = {
  "Smileys & Emotion": "표정・감정",
  "People & Body": "사람・신체",
  "Animals & Nature": "동물・자연",
  "Food & Drink": "음식・음료",
  "Travel & Places": "여행・장소",
  Activities: "활동",
  Objects: "사물",
  Symbols: "기호",
  Flags: "깃발",
};

// 전체 이모지 배열(그룹 순서 유지). c=글자, g=원본 그룹명, k=검색 키워드(이름 + 슬러그 + 한글 오버레이).
export const EMOJI = Object.entries(data).map(([c, m]) => ({
  c,
  g: m.group || "Objects",
  k: `${m.name || ""} ${m.slug || ""} ${EXTRA[c] || ""}`.toLowerCase(),
}));

// 그룹 순서(원본 등장 순서 유지) — 카테고리별 렌더에 사용.
export const EMOJI_GROUPS = EMOJI.reduce((acc, e) => {
  if (!acc.includes(e.g)) acc.push(e.g);
  return acc;
}, []);
